name: ngs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
- bedtools
- bcftools
- bowtie2
- click
- cookiecutter
- deeptools
- fastqc
- fastqsplitter
- homer
- macs2
- multiqc
- numpy>=1.19
- picard-slim
- pip
- pybedtools
- pybigwig
- pysam
- python>=3.8
- samtools>1.7
- seaborn
- snakemake
- star
- subread
- trackhub
- trim-galore
- ucsc-bedgraphtobigwig
- ucsc-bigbedtobed
- ucsc-fetchchromsizes
- pip:
  - git+https://github.com/alsmith151/ucsc_hub_maker.git
  - lanceotron
  - wget