name: ngs
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - macs3
    - wget
  - cgatcore
  - bowtie2
  - samtools
  - deeptools
  - trim-galore
  - macs2
  - fastqc
  - multiqc
  - trackhub
  - seaborn
  - click
  - ucsc-bigbedtobed
  - pybigwig
  - ucsc-fetchchromsizes
  - ucsc-bedtobigbed
  - ucsc-bedgraphtobigwig
  - homer
  - pybedtools
  - subread 
  - star
  
