name: ngs
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2
  - click
  - deeptools
  - fastqc
  - homer
  - macs2
  - multiqc
  - numpy>=1.19
  - trackhub
  - seaborn
  - click
  - cookiecutter
  - picard-slim
  - pip
  - pip:
      - git+https://github.com/alsmith151/ucsc_hub_maker.git
      - lanceotron
      - wget
  - pybedtools
  - pybigwig
  - python>=3.8
  - samtools>1.7
  - seaborn
  - snakemake
  - star
  - subread 
  - trackhub
  - trim-galore
  - ucsc-bedgraphtobigwig
  - ucsc-bedtobigbed
  - ucsc-bigbedtobed
  - ucsc-fetchchromsizes
