executor: local
jobs: 100


use-conda: "False"
software-deployment-method: null
use-apptainer: "False"

show-failed-logs: "True"
printshellcmds: "True"


default-resources: 
    runtime: "1h"
    mem: "3G"