trim_galore:
    threads: 4
    options: --2colour 20 --clip_R1 20 --clip_R2 20

bowtie2:
    threads: 8
    options:

samtools:
    threads: 16
    filter_options: -F 4

featurecounts:
    threads: 16
    options: -F SAF 

cutadapt:
  options: -g 'ACACCG' --cut 0 -l 20 -m 20 -M 20 --discard-untrimmed
  threads: 8