################################# 
# RNA-seq Pipeline Config file #
#################################

version: 1.0

###################################
# Essential configuration options #
###################################

genome:
    name: "{{cookiecutter.genome}}"
    chromosome_sizes: "{{cookiecutter.chromosome_sizes}}"
    indicies: "{{cookiecutter.indicies}}"
    annotation: "{{cookiecutter.gtf}}"

design: "design.csv"

read_type: "{{cookiecutter.read_type}}"
split_fastq: "{{cookiecutter.split_fastq}}"
remove_pcr_duplicates_method: "{{cookiecutter.remove_pcr_duplicates_method}}"
shift_atac_reads: "False"

remove_blacklist: "{{cookiecutter.remove_blacklist}}"
blacklist: "{{cookiecutter.blacklist}}"

make_bigwigs: "{{cookiecutter.make_bigwigs}}"  
pileup_method: "{{cookiecutter.pileup_method}}"

make_ucsc_hub: "{{cookiecutter.make_ucsc_hub}}"
ucsc_hub_details:
    directory: "{{cookiecutter.UCSC_hub_directory}}"
    name: "{{cookiecutter.project_name}}"
    short: "{{cookiecutter.project_name}}"
    long: "{{cookiecutter.project_name}}"
    email: "{{cookiecutter.email}}"
    color_by: "{{cookiecutter.color_by}}"

###################################
#  Optional configuration         #
###################################



#################################
# Tool specific options         #
#################################

trim_galore:
    threads: 4
    options: 

star:
    threads: 4
    options: --quantMode TranscriptomeSAM GeneCounts --outSAMunmapped Within --outSAMattributes Standard

picard:
    threads: 4
    options:

featurecounts:
    threads: 4
    options: -p

homer:
    maketagdirectory:
    makebigwig:

deeptools:
    threads: 8
    alignmentsieve: --minMappingQuality 30 
    # Options passed to deeptools BamCoverage
    # These need to be replaced
    # e.g. --extendReads -bs 1 --normalizeUsing RPKM
    bamcoverage: -bs 1 --normalizeUsing CPM

deseq2:
    project_id: "{{cookiecutter.project_id}}"